reports/urls.py
from django.urls import path

from .views import (
		upload_progress, upload_budget, clear_filters,
		budget_uptake, budget_spend,
		pr_tracking, po_tracking, po_issued,
        performance_pr, performance_po, payments,
        pr_item_details, po_item_details,
	)

from .pdf import views as pdf_views
from .optimization import views as serverside_views

urlpatterns = [
    path('home/pdf/', pdf_views.home, name='home-pdf'),

    path('upload/progress/', upload_progress, name='upload-progress'),
    path('upload/budget/', upload_budget, name='upload-budget'),
    path('clear_filters/', clear_filters, name='clear_filters'),

    path('budget/uptake/', budget_uptake, name='budget-uptake'),
    path('budget/uptake/pdf/', pdf_views.budget_uptake, name='budget-uptake-pdf'),

    path('budget/spend/', budget_spend, name='budget-spend'),
    path('budget/spend/pdf/', pdf_views.budget_spend, name='budget-spend-pdf'),

    path('pr-tracking/', pr_tracking, name='pr-tracking'),
    path('pr-tracking/serverside/', serverside_views.PRTrackingServerSideView.as_view(), name='pr-tracking-serverside'),
    path('pr-tracking/pdf/', pdf_views.pr_tracking, name='pr-tracking-pdf'),

    path('po-tracking/', po_tracking, name='po-tracking'),
    path('po-tracking/serverside/', serverside_views.POTrackingServerSideView.as_view(), name='po-tracking-serverside'),
    path('po-tracking/pdf/', pdf_views.po_tracking, name='po-tracking-pdf'),

    path('po-issued/', po_issued, name='po-issued'),
    path('po-issued/serverside/', serverside_views.POIssuedServerSideView.as_view(), name='po-issued-serverside'),
    path('po-issued/pdf/', pdf_views.po_issued, name='po-issued-pdf'),

    path('performance-pr/', performance_pr, name='performance-pr'),
    path('performance-pr/serverside/', serverside_views.PerformancePRServerSideView.as_view(), name='performance-pr-serverside'),
    path('performance-pr/pdf/', pdf_views.performance_pr, name='performance-pr-pdf'),

    path('performance-po/', performance_po, name='performance-po'),
    path('performance-po/serverside/', serverside_views.PerformancePOServerSideView.as_view(), name='performance-po-serverside'),
    path('performance-po/pdf/', pdf_views.performance_po, name='performance-po-pdf'),

    path('payments/', payments, name='payments'),
    path('payments/serverside/', serverside_views.PaymentsServerSideView.as_view(), name='payments-serverside'),
    path('payments/pdf/', pdf_views.payments, name='payments-pdf'),

    path('pr/details/<int:requisition_id>/', pr_item_details, name='pr_item_details'),

    path('po/details/<int:order_id>/', po_item_details, name='po_item_details'),
]

users/urls.py
"""
This File contains the URL configurations for the ``users`` app.

**URL CONFIGURATIONS** ::

    urlpatterns = [
		path('', home, name='home'),
		# Load the ``home`` view on ``/users/`` request

		path('users/company-setup/', CompanyRegistrationView.as_view(), name='company-setup'),
		# Load the ``CompanyRegistrationView`` on ``/users/company-setup/`` request

		path('users/team/profile/', profile, name='profile'),
		# Load the ``profile`` view on ``/users/team/profile/`` request

		# --- Rest of Configurations follow suit ---
    ]

**END OF URL CONFIGURATIONS**
"""
from django.urls import path
from .views import (
		home, add_team, CompanyRegistrationView, 
		TeamUserUpdateView, TeamUserDeleteView,
		profile
	)

urlpatterns = [
	path('', home, name='home'),
	path('users/company-setup/', CompanyRegistrationView.as_view(), name='company-setup'),

	path('users/team/profile/', profile, name='profile'),

	path('users/team/', add_team, name='team-management'),
	path('users/team/user_<int:pk>/update', TeamUserUpdateView.as_view(), name='update-team-user'),
	path('users/team/user_<int:pk>/delete', TeamUserDeleteView.as_view(), name='delete-team-user'),
]

xbi_analytics/urls.py
"""
xbi_analytics URL Configuration

The ``urlpatterns`` list routes URLs to views. For more information please see: https://docs.djangoproject.com/en/3.1/topics/http/urls/

**URL CONFIGURATIONS** ::

    urlpatterns = [

        path('admin/', admin.site.urls), 
        # ``admin/`` route redirects to the Django admin Site > https://docs.djangoproject.com/en/3.1/ref/contrib/admin/

        path('accounts/', include('allauth.urls')),
        # ``accounts/`` route redirects to `allauth` urls

        path('celery-progress/', include('celery_progress.urls')),
        # celery-progress is responsible for displaying the progress for Celery asynchronous tasks.

        path('', include('users.urls')), 
        # On no specified route, redirect to the users URLS (users.urls)

        path('reports/', include('reports.urls')),
        # ``reports/`` route redirects to the reports URLS (reports.urls)
    ]
    
    # Add media URL settings
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

**END OF URL CONFIGURATIONS**
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('celery-progress/', include('celery_progress.urls')),

    path('reports/', include('reports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
CURRENCIES = (
    ('KES', 'KES'),
    ('USD', 'USD'),
    ('GBP', 'GBP'),
    ('EUR', 'EUR'),
)

SUPPLIER_CATEGORY_CHOICES = (
    ('ZFTV', 'Foreign suppliers'),
    ('ZWGV', 'Local Women suppliers'),
    ('ZYGV', 'Local Youth suppliers'),
    ('ZPWC', 'Local PWD suppliers'),
    ('ZLTV', 'Other Local suppliers'),
)

PROCUREMENT_METHOD_CHOICES = (
    ('Competitive Negotiations', 'Competitive Negotiations'),
    ('Direct Procurement', 'Direct Procurement'),
    ('Electronic Reverse Auction', 'Electronic Reverse Auction'),
    ('Framework Agreements', 'Framework Agreements'),
    ('Open Tender', 'Open Tender'),
    ('Govt to Govt', 'Govt. to Govt.'),
    ('Request For Quotation', 'Request For Quotation'),
    ('Request For Proposal', 'Request For Proposal'),
    ('Restricted Tendering', 'Restricted Tendering'),
    ('Low-Value Procurement', 'Low-Value Procurement'),
    ('Other', 'Other'),
)

def company_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/documents/company_<id>/<filename>
    if instance.company:
    	return 'documents/company_{0}/{1}/'.format(instance.company.id, filename)
    return f'documents/company_tests/{filename}/'

class BaseModel(models.Model):
	company = models.ForeignKey('users.Company', on_delete=models.CASCADE, null=True)
	created_when = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

class Upload(BaseModel):
	processed = models.BooleanField(default=False)

	class Meta:
		abstract = True

class BudgetUpload(Upload):
	budget_file = models.FileField(upload_to=company_directory_path)

class ProgressUpload(Upload):
	progress_file = models.FileField(upload_to=company_directory_path)

class Department(BaseModel):
	name = models.CharField(max_length=120)

	class Meta:
		db_table = 'departments'

	def __str__(self):
		return f'{self.name}'

class Budget(BaseModel):
	department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='budgets')
	amount = models.DecimalField(max_digits=20, decimal_places=2)
	currency = models.CharField(max_length=4, choices=CURRENCIES, default='KES')
	fiscal_year = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1600),
        MaxValueValidator(9999)
    ])

	class Meta:
		db_table = 'budgets'

class Supplier(BaseModel):
	name = models.CharField(max_length=255)
	category = models.CharField(max_length=255, choices=SUPPLIER_CATEGORY_CHOICES, null=True)

	class Meta:
		db_table = 'suppliers'

class Milestone(BaseModel):
	name = models.CharField(max_length=200, null=True)
	descripition = models.TextField(null=True)
	agent = models.CharField(max_length=120)
	release_date = models.DateField()

	class Meta:
		abstract = True

class Requisition(BaseModel):
	department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, related_name='requisitions')

	requisition_number = models.CharField(max_length=20, null=True)
	created_by = models.CharField(max_length=255, null=True)
	currency = models.CharField(max_length=4, choices=CURRENCIES, default='KES', null=True)
	item_description = models.CharField(max_length=255, null=True)
	item_quantity = models.IntegerField(null=True)
	status = models.CharField(max_length=50, null=True)
	value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
	procurement_method = models.CharField(max_length=100, choices=PROCUREMENT_METHOD_CHOICES, null=True)
	requisition_date = models.DateField(null=True)
	release_date = models.DateField(null=True)
	fiscal_year = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1600),
        MaxValueValidator(9999)
    ], null=True)

	class Meta:
		db_table = 'requisitions'
		unique_together = ['company', 'requisition_number', 'item_description', 'item_quantity', 'requisition_date']

	@property
	def processing_days(self):
	    "Returns processing time in days if processed"
	    if self.release_date and self.requisition_date:
	        return (self.release_date - self.requisition_date).days
	    else:
	        return (datetime.datetime.now().date() - self.requisition_date).days

	@property
	def processing_status(self):
	    if self.release_date:
	        return "Processed"
	    else:
	        return "Not Processed"

class Order(BaseModel):
	department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, related_name='orders')
	requisition = models.OneToOneField(Requisition, on_delete=models.CASCADE, null=True)
	supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, related_name='orders')

	order_number = models.CharField(max_length=20, null=True)
	order_quantity = models.IntegerField(null=True)
	quantity_delivered = models.IntegerField(null=True)
	currency = models.CharField(max_length=4, choices=CURRENCIES, default='KES', null=True)
	gross_order_value = models.DecimalField(max_digits=20, decimal_places=2, null=True)
	invoiced_amount = models.DecimalField(max_digits=20, decimal_places=2, null=True)
	paid_amount = models.DecimalField(max_digits=20, decimal_places=2, null=True)
	status = models.CharField(max_length=50, null=True)
	fiscal_year = models.PositiveSmallIntegerField(validators=[
		MinValueValidator(1600),
		MaxValueValidator(9999)
	], null=True)
	order_date = models.DateField(null=True)
	release_date = models.DateField(null=True)
	vendor_delivery_date = models.DateField(null=True)
	po_delivery_date = models.DateField(null=True)

	class Meta:
		db_table = 'orders'
		unique_together = ['company', 'order_number', 'requisition', 'supplier']

	@property
	def processing_days(self):
	    "Returns processing time in days if processed"
	    if self.release_date and self.order_date:
	        return (self.release_date - self.order_date).days
	    elif self.order_date:
	        return (datetime.datetime.now().date() - self.order_date).days
	    else:
	        None

	@property
	def processing_status(self):
	    if self.release_date:
	        return "Processed"
	    else:
	    	return "Not Processed"

	@property
	def delivery_time(self):
	    if self.vendor_delivery_date and self.release_date:
	        return (self.vendor_delivery_date - self.release_date).days
	    else:
	        return None

	@property
	def delivery_status(self):
	    if self.vendor_delivery_date:
	        if self.release_date and self.delivery_time > 90:
	            return "Delivered Late"
	        elif self.release_date and self.delivery_time <= 90:
	            return "Delivered On-time"
	        else:
	            return "Delivered"
	    elif self.release_date:
	        if (datetime.date.today() - self.release_date).days > 90:
	            return "Late"
	        else:
	            return "On-going Delivery"
	    else:
	        return None

	@property
	def payment_status(self):
	    if self.paid_amount:
	        return "Paid"
	    elif self.invoiced_amount:
	        return "Due for payment"
	    else:
	        return "Pending Invoice"

class PRMilestone(Milestone):
	requisition = models.ForeignKey(Requisition, on_delete=models.CASCADE, null=True, related_name='milestones')

class POMilestone(Milestone):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, related_name='milestones')

reports/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field, Div, ButtonHolder, HTML

from .models import ProgressUpload, BudgetUpload

class ProgressUploadForm(forms.ModelForm):
	progress_file = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))
	class Meta:
		model = ProgressUpload
		fields = ['progress_file']
		
class BudgetUploadForm(forms.ModelForm):
	budget_file = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))
	class Meta:
		model = BudgetUpload
		fields = ['budget_file']

	def __init__(self, *args, **kwargs):
	    super(BudgetUploadForm, self).__init__(*args, **kwargs)
	    self.helper = FormHelper()
	    self.helper.form_tag = False
	    self.helper.layout = Layout(
	    	Row(
				Column(
					Field('budget_file', css_id="", css_class=""),
    			)
	    	)
	    )

class UploadWizardForm(forms.Form):
	progress_work_book = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))
	budget_work_book = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))

	def __init__(self, *args, **kwargs):
	    super(UploadWizardForm, self).__init__(*args, **kwargs)
	    self.helper = FormHelper()
	    self.helper.form_tag = False
	    self.helper.layout = Layout(
	    	Row(
				Column(
					Field('budget_work_book', css_id="", css_class=""),
    			),
				Column(
					Field('progress_work_book', css_id="", css_class=""),
    			),
	    	),
	    	ButtonHolder(
		    	HTML(
		    		'{% include "users/forms/wizards/_buttons.html" %}'
		    	)
	    	)
	    )

templates/reports/details/po_item_details.html
{% extends "layout/layout.html" %}
{% load humanize %}

{% block header %}
<div class="section-header">
	<h5 class="text-title">Order Details</h5>
	<div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></div>
      <div class="breadcrumb-item"><a href="{% url 'po-tracking' %}">Orders Tracking</a></div>
      <div class="breadcrumb-item">{{po.order_number}}</div>
    </div>
</div>
	
{% endblock header %}

{% block content %}	
	<div class="section-body">
		<div class="card">
			<div class="card-body">				
		        <div class="float-left">                        
		            <div>
		                <h3>Order Status</h3>
		            </div>
		        </div>
		        <div class="float-right">
		            <a href="{# {% url pdf_url po.id %} #}" class="btn btn-outline-dark btn-lg">
	                    <span class="fas fa-file-export"></span> Export
	                </a>
		        </div>
			</div>
	    </div>

	    <div class="row">
	    	<div class="col-md-8">
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="progress-bar"></div>
                    	<div>{{po.processing_days}} Processing Days</div>
                    </div>
	    		</div>
	    		{% if po.vendor_delivery_date %}
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		                        <thead>
		                            <tr><th colspan="2">Delivery Performance</th></tr>
		                        </thead>
		                        <tbody>
		                        	<tr>
		                        		<td>Time Score</td>
		                        		<td>{{po.time_score}}</td>
		                        	</tr>
		                        	<tr>
		                        		<td>Quantity Score</td>
		                        		<td>{{po.quantity_score}}</td>
		                        	</tr>
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		                        <thead>
		                            <tr><th colspan="2">Payment Details</th></tr>
		                        </thead>
		                        <tbody>
		                        	<tr>
		                        		<td>Payment Status</td>
		                        		<td>{{po.payment_time_status}}</td>
		                        	</tr>
		                        	{% if po.payment_date %}
		                        	<tr>
		                        		<td>Payment Date</td>
		                        		<td>{{po.payment_date}}</td>
		                        	</tr>                  		
		                        	{% endif %}
		                        	<tr>
		                        		<td>Invoiced Amount</td>
		                        		<td>{{po.invoiced_amount|intcomma}}</td>
		                        	</tr>
		                        	<tr>
		                        		<td>Paid Amount</td>
		                        		<td>{{po.paid_amount|intcomma}}</td>
		                        	</tr>
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    		{% endif %}

	    		{% if po.release_date %}
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		    					<thead>Delivery Details</thead>
		    					<tbody>
		    						<tr>
		    							<td>Delivery Status</td>
		    							<td>{{po.delivery_time_status}}</td>
		    						</tr>
		    						<tr>
		    							<td>Delivery Date</td>
		    							<td>{{po.vendor_delivery_date}}</td>
		    						</tr>
		    						<tr>
		    							<td>Expected Delivery Date</td>
		    							<td>{{expected_delivery_date}}</td>
		    						</tr>
		    					</tbody>
		    				</table>
	    				</div>
	    			</div>
	    		</div>
	    		{% endif %}
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		    					<thead>Processing Details</thead>
		    					<tbody>
		    						<tr>
		    							<td>Processing Status</td>
		    							<td>{{po.processing_time_status}}</td>
		    						</tr>
		    						<tr>
		    							<td>Current Stage</td>
		    							<td>{{po.processing_level}}</td>
		    						</tr>
		    					</tbody>
		    				</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		    					<thead>Order Details</thead>
		    					<tbody>
		    						<tr>
		    							<td>Order Number</td>
		    							<td>{{po.order_number}}</td>
		    						</tr>
		    						<tr>
		    							<td>Order Date</td>
		    							<td>{{po.order_date}}</td>
		    						</tr>
		    						<tr>
		    							<td>Final Order Release Date</td>
		    							<td>{{po.release_date}}</td>
		    						</tr>
		    						<tr>
		    							<td>Vendor</td>
		    							<td>{{po.supplier.name|title|default:"No supplier"}}</td>
		    						</tr>
		    						<tr>
		    							<td>Supplier Group</td>
		    							<td>{{po.supplier.get_category_display}}</td>
		    						</tr>
		    						<tr>
		    							<td>Procurement Method</td>
		    							<td>
		    								{{po.procurement_method}}
		    							</td>
		    						</tr>
		    						<tr>
		    							<td>Requisition Number</td>
		    							<td>{{po.requisition.requisition_number}}</td>
		    						</tr>
		    					</tbody>
		    				</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
	                        	<!-- Table Header  -->
		                        <thead>
			                        <tr>
			                            <th>Item</th>
			                            <th>Quantity</th>
			                            <th>Order Unit</th>
			                            <th>Amount (KES)</th>
			                        </tr>
		                        </thead>

	                        	<!-- Table Body  -->
		                        <tbody>
			                        <tr>
			                            <td>{{po.requisition.item_description|title}}</td>
			                            <td>{{po.requisition.item_quantity}}</td>
			                            <td>{{po.requisition.item_unit}}</td>
			                            <td>{{po.gross_order_value|intcomma}}</td>
			                        </tr>
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
	                   		<!-- Table Header  -->
			                    <thead>
				                    <tr>
				                        <th>Stage</th>
				                        <th>Release Date</th>
				                        <th>Days</th>
				                        <th>Manager</th>
				                    </tr>
			                    </thead>
	                    		<!-- Table Body  -->
			                    <tbody>
			                    	{% for milestone in po.milestones.all %}			                    		
					                    <tr>
					                        <td>{{milestone.name}}</td>
					                        <td>{{milestone.release_date}}</td>
					                        <td>{{milestone.processing_days}}</td>
					                        <td>{{milestone.description}}</td>
					                    </tr>
			                    	{% endfor %}				              
			                    </tbody>
	                		</table>
	    				</div>
	    			</div>
	    		</div>
	    	</div>
	    	<div class="col-md-4">
	    		<div class="card">
	    			<div class="card-header">
	    				<h6>Milestone Stages</h6>
	    			</div>
	    		</div>
	    		<div class="activities">
	    			<div class="activity">
	    				{% for milestone in po.milestones.all %}
		    				<div class="activity-icon bg-success text-white shadow-success">
	                      		<i class="fas fa-arrow-down"></i>
	                    	</div>
	                    	<div class="activity-detail">
	                      		<div class="mb-2">
			                        <span class="text-job">{{milestone.name}}</span>                  
	                    		</div>
	                		</div>	    					
	    				{% endfor %}
	    			</div>
	    		</div>
	    	</div>
	    </div>
    </div>
{% endblock content %}
{% block customjs %}
<script>
	$('#po-link,#po-tracking-link').addClass('active');
</script>
	
{% endblock customjs %}

templates/reports/details/pr_item_details.html
{% extends "layout/layout.html" %}
{% load humanize %}

{% block header %}
<div class="section-header">
	<h5 class="text-title">Requisition Details</h5>
	<div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></div>
      <div class="breadcrumb-item"><a href="{% url 'po-tracking' %}">Requisition Tracking</a></div>
      <div class="breadcrumb-item">{{pr.requisition_number}}</div>
    </div>
</div>
	
{% endblock header %}

{% block content %}	
	<div class="section-body">
		<div class="card">
			<div class="card-body">				
		        <div class="float-left">                        
		            <div>
		                <h3 class="">Request Status</h3>
		            </div>
		        </div>
		        <div class="float-right">
		            <a href="{# {% url pdf_url pr.id %} #}" class="btn btn-outline-dark btn-lg">
	                    <span class="fas fa-file-export"></span> Export
	                </a>
		        </div>
			</div>
	    </div>

	    <div class="row">
	    	<div class="col-md-8">
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="progress-bar"></div>
                    	<div>{{pr.processing_days}} Processing Days</div>
                    </div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
		                        <thead class="data-text">
		                            <tr><th colspan="2">Requisition Details</th></tr>
		                        </thead>
		                        <tbody>	                        	
			                        <tr>
			                            <td>Requisition Number:</td>
			                            <td>{{pr.requisition_number}}</td>
			                        </tr>
			                        <tr>
			                            <td>Status:</td>
			                            <td>{{pr.processing_time_status}}</td>
			                        </tr>
			                        <tr>
			                            <td>Current Stage:</td>
			                            <td>{{pr.current_stage}}<br></td>
			                        </tr>
			                        <tr>
			                            <td>Requisition Date:<br></td>
			                            <td>{{pr.requisition_date}}<br></td>
			                        </tr>
			                        <tr>
			                            <td>Department:</td>
			                            <td>{{pr.department.name}}<br></td>
			                        </tr>
			                        <tr>
			                            <td>Request Created By:<br></td>
			                            <td>{{pr.created_by}}<br></td>
			                        </tr>
			                        <tr>
			                            <td>Final PR Release Date:<br></td>
			                            <td>{{pr.release_date|default:"None"}}<br></td>
			                        </tr>
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">
	                        	<!-- Table Header  -->
		                        <thead>
			                        <tr>
			                            <th>Item</th>
			                            <th>Quantity</th>
			                            <th>Amount (KES)</th>
			                        </tr>
		                        </thead>

	                        	<!-- Table Body  -->
		                        <tbody>
			                        <tr>
			                            <td>{{pr.item_description|lower|capfirst}}</td>
			                            <td>{{pr.item_quantity}}</td>
			                            <td>{{pr.value|intcomma}}</td>
			                        </tr>
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="card">
	    			<div class="card-body">
	    				<div class="table-responsive">	    					
		    				<table class="table">

	                        	<!-- Table Header  -->
		                        <thead>
			                        <tr class="">
			                            <th>Stage</th>
			                            <th>Release Date</th>
			                            <th>Days</th>
			                            <th>Description</th>
			                        </tr>
		                        </thead>

		                        <!-- Table Body  -->
		                        <tbody>
		                        	{% for milestone in pr.milestones.all %}			                    		
					                    <tr>
					                        <td>{{milestone.name}}</td>
					                        <td>{{milestone.release_date}}</td>
					                        <td>{{milestone.processing_days}}</td>
					                        <td>{{milestone.description}}</td>
					                    </tr>
			                    	{% endfor %}
		                        </tbody>
	                    	</table>
	    				</div>
	    			</div>
	    		</div>
	    	</div>
	    	<div class="col-md-4">
	    		<div class="card">
	    			<div class="card-header">
	    				<h6>Milestone Stages</h6>
	    			</div>
	    		</div>
	    		<div class="activities">
	    			{% for milestone in po.milestones.all %}
	    				<div class="activity-icon bg-success text-white shadow-success">
                      		<i class="fas fa-arrow-down"></i>
                    	</div>
                    	<div class="activity-detail">
                      		<div class="mb-2">
		                        <span class="text-job">{{milestone.name}}</span>                  
                    		</div>
                		</div>	    					
    				{% endfor %}
	    		</div>
	    	</div>
	    </div>
    </div>
{% endblock content %}
{% block customjs %}
<script>
	$('#pr-link').addClass('active');
	$('.table').DataTable();
</script>
	
{% endblock customjs %}